# Generated by Django 5.0.4 on 2025-03-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('request_method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('http_version', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField()),
            ],
        ),
    ]
